spring:
  datasource:
    url: jdbc:h2:mem:db
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

cors:
  originPatterns: http://localhost:4200

jwt:
  auth:
    secret-key: rfv3T}>Z]u!(@CY
    expiration-time: 3600000